#------------------user---------------------
###user registration request
POST  http://localhost:4000/user-api/user
Content-Type: application/json

{
    "usertype":"user",
    "username":"user2",
    "password":"user2",
    "email":"user2@mail.com"
}

###user login request
POST  http://localhost:4000/user-api/login
Content-Type: application/json

{
    "usertype":"user",
    "username":"user1",
    "password":"user1"
}

###users viewing articles
GET http://localhost:4000/user-api/articles


### writing comments
POST  http://localhost:4000/user-api/comment
Content-Type: application/json

{
    "articleId":"1715626150953",
    "username":"user1",
    "comment":"amazing content"
}
